import { useState } from "react";
import { ChevronDown, ChevronUp, ExternalLink } from "lucide-react";
import { useTranslation } from "@/contexts/I18nContext";

type Copy = { decision:string; situation:string; observation:string; oldMethod:string; branches:[string,string,string]; probe:string; result:string; revisit:string; source:string; sourceDate:string; sourceUrl:string };
type Challenge = { id:string; ru:Copy; en:Copy };

// Editorially reviewed local candidate. Source supports only `observation`; the
// remaining fields are conditional ways to examine one operating decision.
const CHALLENGES: Challenge[] = [
  { id:"agent-authority", ru:{ decision:"Можно ли дать агенту право действовать от имени процесса?", situation:"Вы хотите дать агенту доступ к данным, инструменту или внешней операции — не только к подготовке черновика.", observation:"Исследование Anthropic 2025 года в контролируемой среде показало: при доступе к чувствительным данным и email часть моделей при специально созданных конфликтах целей совершала вредные действия. Это не инцидент у вашей организации.", oldMethod:"Проверки текста недостаточно, когда ошибка возникает из-за выданного полномочия. Контроль нужен на всём контуре: данные → инструмент → действие → человек.", branches:["Оставить агенту подготовку; сотрудник выполняет действие.","Дать одну обратимую операцию с владельцем и подтверждением.","Не давать доступ, пока нет владельца и способа заметить ошибку."], probe:"Для одного процесса зафиксировать: данные, инструмент, действие, подтверждающего и след проверки. Первый проход — черновик или тестовая среда.", result:"Видно, у каждого ли действия есть владелец, журнал и право отмены.", revisit:"Новый доступ, действие без человека или смена системы.", source:"Anthropic, Agentic Misalignment", sourceDate:"20 июня 2025", sourceUrl:"https://www.anthropic.com/research/agentic-misalignment" }, en:{ decision:"Can an agent act on behalf of this process?", situation:"You are considering access to data, a tool, or an external operation, rather than drafting only.", observation:"Anthropic’s 2025 controlled experiment found that, with sensitive data and email access, some models took harmful actions under deliberately created goal conflicts. This is not an incident in your organisation.", oldMethod:"Reviewing text is insufficient when the error is an authority that was granted. Control belongs to the whole chain: data → tool → action → person.", branches:["Keep the agent in drafting mode; a person acts.","Allow one reversible operation with an owner and confirmation.","Do not grant access until ownership and error detection exist."], probe:"For one process, record the data, tool, action, confirmer, and review trace. The first run is a draft or test environment.", result:"You can see whether every action has an owner, a log, and a way to cancel it.", revisit:"A new permission, action without a person, or system change.", source:"Anthropic, Agentic Misalignment", sourceDate:"20 June 2025", sourceUrl:"https://www.anthropic.com/research/agentic-misalignment" } },
  { id:"public-content", ru:{ decision:"Кто отвечает за публичный AI-контент и обращение пользователя?", situation:"Вы ведёте публичный поток: сайт, поддержку, рекламу, медиа или HR-коммуникацию с AI.", observation:"Еврокомиссия выпустила разъяснения о прозрачности AI-систем. Это основание проверить требования для своего сценария, а не готовый вывод о применимости к вашему продукту. Маршрут обработки обращений ниже — редакторская рекомендация, а не изложение обязанности по Article 50.", oldMethod:"Одна техническая метка не объясняет, кто раскрывает характер взаимодействия, принимает обращение и фиксирует решение.", branches:["Зафиксировать основание, почему после первичной проверки изменения не нужны.","Связать один экран с владельцем, юрисдикцией, раскрытием и обращением.","При неясном scope остановить изменение до юридической сверки."], probe:"Для одного маршрута описать: точка контакта, действие AI, видимое пользователю, страны, владелец и путь обращения.", result:"Есть именованный поток и решение: изменить, не изменять или передать на оценку.", revisit:"Новый публичный сценарий, юрисдикция, роль поставщика или обращение.", source:"European Commission, Article 50 guidance", sourceDate:"20 июля 2026", sourceUrl:"https://digital-strategy.ec.europa.eu/en/library/guidelines-transparency-obligations-providers-and-deployers-ai-systems" }, en:{ decision:"Who owns public AI content and a user’s request?", situation:"You operate a public site, support, advertising, media, or HR flow with AI.", observation:"The European Commission has published guidance on AI-system transparency. This is a reason to check the requirements for your scenario, not a determination that they apply to your product. The request-handling route below is an editorial recommendation, not a statement of an Article 50 obligation.", oldMethod:"A technical label alone does not identify who explains the interaction, receives a request, or records a decision.", branches:["Record why no change is needed after an initial applicability check.","Connect one screen to an owner, jurisdiction, disclosure, and request route.","Pause the change for legal review when scope is unclear."], probe:"For one journey, record the contact point, AI action, what the user sees, countries, owner, and request route.", result:"There is a named flow and a decision: change, do not change, or seek review.", revisit:"A new public scenario, jurisdiction, provider role, or user request.", source:"European Commission, Article 50 guidance", sourceDate:"20 July 2026", sourceUrl:"https://digital-strategy.ec.europa.eu/en/library/guidelines-transparency-obligations-providers-and-deployers-ai-systems" } },
  { id:"capacity-commitment", ru:{ decision:"Стоит ли брать долгий контракт на вычислительные мощности?", situation:"Вы выбираете собственные мощности, долгий контракт или гибкую облачную закупку.", observation:"IEA в сценарном отчёте 2025 года описывает рост мирового спроса дата-центров на электроэнергию и более долгий цикл энергетической инфраструктуры. Это не доказывает дефицит на конкретной площадке.", oldMethod:"Сравнения цены GPU и облака недостаточно, если решение включает срок, регион, подключение, загрузку и условия выхода.", branches:["Оставить гибкий облачный режим при нестабильной нагрузке.","Резервировать мощность только для подтверждённого сценария с условиями выхода.","Отложить обязательство, пока неизвестны регион, подключение или цена простоя."], probe:"Для одного процесса сравнить нагрузку, мощность, регион, поставщика, срок, цену простоя и условия изменения контракта.", result:"Можно назвать выбранный вариант, его предпосылку и событие, которое отменит выбор.", revisit:"Нагрузка, предложение поставщика, регион, срок подключения или цена простоя.", source:"IEA, Energy and AI", sourceDate:"10 апреля 2025", sourceUrl:"https://www.iea.org/reports/energy-and-ai" }, en:{ decision:"Should you take a long compute-capacity commitment?", situation:"You are choosing owned capacity, a long contract, or flexible cloud procurement.", observation:"IEA’s 2025 scenario report describes rising global data-centre electricity demand and a longer energy-infrastructure cycle. It does not establish scarcity at a specific site.", oldMethod:"Comparing GPU and cloud price is insufficient when the decision includes term, region, connection, utilisation, and exit conditions.", branches:["Keep flexible cloud procurement while demand is unstable.","Reserve capacity only for a confirmed scenario with exit conditions.","Defer the commitment while region, connection, or downtime cost is unknown."], probe:"For one process compare demand, capacity, region, provider, lead time, downtime cost, and contract-change conditions.", result:"You can name the option, its assumption, and the event that would reverse it.", revisit:"Demand, provider offer, region, connection lead time, or downtime cost.", source:"IEA, Energy and AI", sourceDate:"10 April 2025", sourceUrl:"https://www.iea.org/reports/energy-and-ai" } },
];

export default function DecisionChallenges() {
  const { locale } = useTranslation(); const isEn = locale === "en"; const [selected, setSelected] = useState(0); const [details, setDetails] = useState(false);
  const item = CHALLENGES[selected]; const c = isEn ? item.en : item.ru;
  return <div className="container"><div className="mb-5"><p className="text-xs font-mono text-primary/70 tracking-widest uppercase">{isEn ? "Decision challenges" : "Вызовы для решения"}</p><h3 className="mt-2 text-xl sm:text-2xl font-heading font-bold">{isEn ? "Which decision is in front of you?" : "Какое решение стоит перед вами?"}</h3><p className="mt-2 text-sm text-muted-foreground">{isEn ? "Choose the situation you have met in your work." : "Выберите ситуацию, с которой столкнулись в работе."}</p></div>
    <div className="grid gap-2 sm:grid-cols-3">{CHALLENGES.map((x,i)=>{const v=isEn?x.en:x.ru; return <button key={x.id} onClick={()=>{setSelected(i);setDetails(false)}} aria-pressed={selected===i} className={`rounded-xl border p-4 text-left text-sm transition-colors ${selected===i?"border-primary bg-primary/10":"border-border/50 bg-card/40 hover:border-primary/40"}`}>{v.decision}</button>})}</div>
    <article className="mt-4 rounded-xl border border-primary/30 bg-card/60 p-4 sm:p-6"><p className="text-xs font-mono text-amber-300">{isEn?"Source and boundary":"На чём основан разбор"} · {c.sourceDate}</p><h4 className="mt-2 text-lg font-heading font-bold">{c.decision}</h4><p className="mt-2 text-sm text-foreground/80">{c.situation}</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><div><h5 className="font-medium">{isEn?"What the source supports":"Что подтверждает источник"}</h5><p className="mt-1 text-sm text-muted-foreground">{c.observation}</p></div><div><h5 className="font-medium">{isEn?"Why the old method is insufficient":"Почему прежний способ недостаточен"}</h5><p className="mt-1 text-sm text-muted-foreground">{c.oldMethod}</p></div></div>
      <div className="mt-5 border-t border-border/40 pt-4"><h5 className="font-medium">{isEn?"Decision branches":"Развилка решения"}</h5><ul className="mt-2 space-y-2 text-sm text-foreground/80">{c.branches.map((b,i)=><li key={b} className="rounded-lg bg-background/40 p-3"><span className="mr-2 font-mono text-primary">{i+1}</span>{b}</li>)}</ul></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-lg border border-border/40 p-3"><h5 className="font-medium">{isEn?"Reversible probe":"Обратимая проба"}</h5><p className="mt-1 text-sm text-muted-foreground">{c.probe}</p></div><div className="rounded-lg border border-border/40 p-3"><h5 className="font-medium">{isEn?"What to observe":"Наблюдаемый результат"}</h5><p className="mt-1 text-sm text-muted-foreground">{c.result}</p><p className="mt-2 text-xs text-amber-300">{isEn?"Revisit: ":"Пересмотреть: "}{c.revisit}</p></div></div>
      <button onClick={()=>setDetails(!details)} aria-expanded={details} className="mt-5 inline-flex items-center gap-2 text-sm text-primary">{isEn?"Source details and limits":"Источник и границы"}{details?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button>{details&&<p className="mt-2 text-xs text-muted-foreground"><a className="inline-flex items-center gap-1 text-primary" href={c.sourceUrl} target="_blank" rel="noreferrer">{c.source}<ExternalLink size={12}/></a> · {isEn?"The source supports the observation, not a conclusion about your organisation.":"Источник подтверждает наблюдение, а не вывод о вашей организации."}</p>}
    </article></div>
}
